### ISSUE TITLE
Use CSS Variable style binding

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#97]
Change binding syntax in CSS files to bind to css variables.

**What is the motivation / use case for changing the behavior?**
This will make our bindings parse as valid CSS, solving issues we currently have with Webpack and PostCSS exhibited in #50 and #81.

**Requirements**

> *W3C CSS Variable Structure*
> ```
> var( <custom-property-name> [, <declaration-value> ]? )
> ```

Aurelia UX should parse the incoming stylesheet and set up and replace CSS variables at runtime.

In the future parsing of the stylesheet will become unnecessary when CSS Variables become more widely supported so the implementation in the stylesheets should be compliant with current CSS Variables

**Example**
```css
test {
  margin: 0;
  height: 100%;
  background-color: ${ foreground || '#fff'};
  color: #fff;
  flex: 1;
}
```
Becomes
```css
test {
  margin: 0;
  height: 100%;
  background-color: var(--foreground, #fff);
  color: #fff;
  flex: 1;
}
```
